CREATE TABLE IF NOT EXISTS App (
  id        CHAR(36)     NOT NULL,
  name      VARCHAR(100) NOT NULL,
  createdAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt DATETIME     NULL     DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX idx_app_name (name),
  INDEX idx_app_deletedAt (deletedAt)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
